--Part – A:
--1. List all books with their authors.

SELECT B.TITLE, A.AUTHORNAME
FROM BOOK B
JOIN AUTHOR A ON B.AUTHORID = A.AUTHORID;

--2. List all books with their publishers.

SELECT B.TITLE, P.PUBLISHERNAME
FROM BOOK B
JOIN PUBLISHER P ON B.PUBLISHERID = P.PUBLISHERID;

--3. List all books with their authors and publishers.

SELECT B.TITLE, A.AUTHORNAME, P.PUBLISHERNAME
FROM BOOK B
JOIN AUTHOR A ON B.AUTHORID = A.AUTHORID
JOIN PUBLISHER P ON B.PUBLISHERID = P.PUBLISHERID;

--4. List all books published after 2010 with their authors and publisher and price.

SELECT B.TITLE, A.AUTHORNAME, P.PUBLISHERNAME, B.PRICE
FROM BOOK B
JOIN AUTHOR A ON B.AUTHORID = A.AUTHORID
JOIN PUBLISHER P ON B.PUBLISHERID = P.PUBLISHERID
WHERE B.PUBLICATIONYEAR > 2010;

--5. List all authors and the number of books they have written.

SELECT A.AUTHORNAME, COUNT(B.BOOKID) AS NUMBER_OF_BOOKS
FROM AUTHOR A
LEFT JOIN BOOK B ON A.AUTHORID = B.AUTHORID
GROUP BY A.AUTHORID, A.AUTHORNAME;

--6. List all publishers and the total price of books they have published.

SELECT P.PUBLISHERNAME, SUM(B.PRICE) AS TOTAL_PRICE
FROM PUBLISHER P
LEFT JOIN BOOK B ON P.PUBLISHERID = B.PUBLISHERID
GROUP BY P.PUBLISHERID, P.PUBLISHERNAME;


--7. List authors who have not written any books.

SELECT A.AUTHORNAME
FROM AUTHOR A
LEFT JOIN BOOK B ON A.AUTHORID = B.AUTHORID
WHERE B.BOOKID IS NULL;

--8. Display the total number of books written by each author along with the average price of their books.

SELECT A.AUTHORNAME,
       COUNT(B.BOOKID) AS TOTAL_BOOKS,
       AVG(B.PRICE) AS AVERAGE_PRICE
FROM AUTHOR A
LEFT JOIN BOOK B ON A.AUTHORID = B.AUTHORID
GROUP BY A.AUTHORID, A.AUTHORNAME;

--9. lists each publisher along with the total number of books they have published, sorted from highest to lowest.

SELECT P.PUBLISHERNAME,
       COUNT(B.BOOKID) AS TOTAL_BOOKS
FROM PUBLISHER P
LEFT JOIN BOOK B ON P.PUBLISHERID = B.PUBLISHERID
GROUP BY P.PUBLISHERID, P.PUBLISHERNAME
ORDER BY TOTAL_BOOKS DESC;

--10. Display number of books published each year.

SELECT PUBLICATIONYEAR, COUNT(*) AS NUMBER_OF_BOOKS
FROM BOOK
GROUP BY PUBLICATIONYEAR
ORDER BY PUBLICATIONYEAR;
