--Part – A:
--1. Display players who belong to teams located in ‘Mumbai’.

SELECT P.PLAYER_ID, P.PLAYER_FIRST_NAME, P.PLAYER_LAST_NAME, T.TEAM_NAME
FROM PLAYER P
JOIN TEAM T ON P.TEAM_ID = T.TEAM_ID
JOIN STADIUM S ON T.HOME_STADIUM_ID = S.STADIUM_ID
WHERE S.STADIUM_CITY = 'Mumbai';

--2. Display all teams and players.

SELECT T.TEAM_NAME, P.PLAYER_FIRST_NAME
FROM TEAM T
LEFT JOIN PLAYER P ON T.TEAM_ID = P.TEAM_ID;

--3. Display players along with team wins and stadium city.

SELECT P.PLAYER_FIRST_NAME, P.PLAYER_LAST_NAME,
       T.TEAM_NAME, T.TEAM_WINS, S.STADIUM_CITY
FROM PLAYER P
JOIN TEAM T ON P.TEAM_ID = T.TEAM_ID
JOIN STADIUM S ON T.HOME_STADIUM_ID = S.STADIUM_ID;

--4. Display team name and number of players in each team.

SELECT T.TEAM_NAME, COUNT(P.PLAYER_ID) AS NUMBER_OF_PLAYERS
FROM TEAM T
LEFT JOIN PLAYER P ON T.TEAM_ID = P.TEAM_ID
GROUP BY T.TEAM_NAME;

--5. Display team name, coach, and number of bowlers in each team.

SELECT T.TEAM_NAME, T.TEAM_COACH,
       COUNT(CASE WHEN P.PLAYER_ROLE = 'Bowler' THEN 1 END) AS NUMBER_OF_BOWLERS
FROM TEAM T
LEFT JOIN PLAYER P ON T.TEAM_ID = P.TEAM_ID
GROUP BY T.TEAM_NAME, T.TEAM_COACH;


--6. Display team name with count of batsmen, bowlers, and all-rounders.

SELECT T.TEAM_NAME,
       COUNT(CASE WHEN P.PLAYER_ROLE = 'Batsman' THEN 1 END) AS BATSMEN,
       COUNT(CASE WHEN P.PLAYER_ROLE = 'Bowler' THEN 1 END) AS BOWLERS,
       COUNT(CASE WHEN P.PLAYER_ROLE = 'All-rounder' THEN 1 END) AS ALL_ROUNDERS
FROM TEAM T
LEFT JOIN PLAYER P ON T.TEAM_ID = P.TEAM_ID
GROUP BY T.TEAM_NAME;

--7. Display stadiums where teams have won more than 10 matches.

SELECT S.STADIUM_NAME, S.STADIUM_CITY, T.TEAM_NAME, T.TEAM_WINS
FROM STADIUM S
JOIN TEAM T ON S.STADIUM_ID = T.HOME_STADIUM_ID
WHERE T.TEAM_WINS > 10;


--8. Display team name and number of players whose matches played is greater than 25.

SELECT T.TEAM_NAME, COUNT(P.PLAYER_ID) AS NUMBER_OF_PLAYERS
FROM TEAM T
LEFT JOIN PLAYER P
ON T.TEAM_ID = P.TEAM_ID
AND P.PLAYER_MATCHES_PLAYED > 25
GROUP BY T.TEAM_NAME;

--9. Display team name and total number of players having jersey number greater than 30.

SELECT T.TEAM_NAME, COUNT(P.PLAYER_ID) AS NUMBER_OF_PLAYERS
FROM TEAM T
LEFT JOIN PLAYER P
ON T.TEAM_ID = P.TEAM_ID
AND P.PLAYER_JERSEY_NUMBER > 30
GROUP BY T.TEAM_NAME;

--10. Display team name and total matches played by its players.

SELECT T.TEAM_NAME,
       COALESCE(SUM(P.PLAYER_MATCHES_PLAYED), 0) AS TOTAL_MATCHES_PLAYED
FROM TEAM T
LEFT JOIN PLAYER P ON T.TEAM_ID = P.TEAM_ID
GROUP BY T.TEAM_NAME;
